---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup.yml

    - name: Find VPCs by Tag
      amazon.aws.ec2_vpc_net_info:
        filters:
          tag:Project: AnsibleCloudProject
      register: vpc_facts

    - name: Find all resources with the same tag
      amazon.aws.ec2_tag_facts:
        filters:
          key: Project
          value: AnsibleCloudProject
      register: tag_resources

    - name: Delete all resources based on tags
      block:
        - name: Check resource type and delete
          ansible.builtin.include_tasks: delete_resources.yml
          vars:
            resource_type: "{{ item.resource_type }}"
            resource_id: "{{ item.id }}"
            region: "{{ region }}"
          loop: "{{ tag_resources.resources }}"
          loop_control:
            label: "{{ item.resource_type }}: {{ item.id }}"
      when: tag_resources.resources | length > 0
