- name: Setup instance profile
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import S3 Bucket name
      ansible.builtin.include_vars:
        file: vars/vpc-output_vars


    - name: Create IAM Role for EC2 with Policy Attached
      amazon.aws.iam_role:
        name: "EC2S3AccessRole"
        assume_role_policy_document: >
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Service": "ec2.amazonaws.com"
                },
                "Action": "sts:AssumeRole"
              }
            ]
          }
      register: role_result

    - name: Create IAM Policy
      amazon.aws.iam_policy:
        iam_type: role
        iam_name: "EC2S3AccessRole"
        policy_name: "S3ACCESS"
        policy_json: >
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Action": [
                  "s3:ListBucket",
                  "s3:GetObject",
                  "s3:PutObject"
                ],
                "Resource": [
                  "arn:aws:s3:::{{s3OUT}}",
                  "arn:aws:s3:::{{s3OUT}}/*"
                ]
              }
            ]
          }
      register: policy_result


    - name: Create Instance Profile
      amazon.aws.iam_instance_profile:
        name: "EC2S3AccessInstanceProfile"
        role: "{{ role_result.role.name }}"
        path: "/"
      register: instance_profile_result

    - name: Add a new variable to the vars/vars-output_vars file
      lineinfile:
        path: "vars/vpc-output_vars"
        line: "instance_profile_arn: {{ instance_profile_result.iam_instance_profile.arn }}"
        state: present
