---
- name: Update hosts, inventory and prometheus config
  hosts: localhost
  connection: local
  gather_facts: no
  become: true
  tasks:
    - name: Import IDs
      include_vars: ../vars/vpc-output_vars
    - name: Retrieve details of the Auto Scaling Group
      amazon.aws.autoscaling_group_info:
        name: "{{asgOUT}}"  # Replace with your ASG name
        region: "{{ region }}"
      register: asg_out

    - name: Gather information about ASG instances
      amazon.aws.ec2_instance_info:
        instance_ids: "{{ item.instance_id }}"
        region: "{{ region }}"
      loop: "{{ asg_out.results | map(attribute='instances') | flatten }}"
      register: ec2_info

    - name: Insert Private IPs of ASG Instances to a File
      ansible.builtin.copy:
        content: |
          {% for result in ec2_info.results %}
          web{{ loop.index }}: {{ result.instances[0].private_ip_address }}
          {% endfor %}
        dest: "provisioning/group_vars/hostsip"

    - name: Create Dynamic Inventory
      ansible.builtin.copy:
        content: |
          {% for result in ec2_info.results %}
          web{{ loop.index }} ansible_host={{ result.instances[0].private_ip_address }}
          {% endfor %}
          cntl ansible_host=127.0.0.1 ansible_connection=local
          
          [websrvgrp]
          {% for result in ec2_info.results %}
          web{{ loop.index }}
          {% endfor %}
          
          [control]
          cntl
          
          [stack_inst:children]
          websrvgrp
          
          [stack_inst:vars]
          ansible_user=ubuntu
          ansible_ssh_private_key_file=/var/lib/jenkins/shared_workspace/provisioning/site_loginkey.pem
        dest: "provisioning/inventory"

    - name: Backup the existing prometheus.yml
      ansible.builtin.copy:
        src: /etc/prometheus/prometheus.yml
        dest: /etc/prometheus/prometheus.yml.bak

    - name: Generate list of node exporters from inventory
      ansible.builtin.template:
        src: provisioning/templates/prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
        mode: '0644'

    - name: Update prometheus config files
      ansible.builtin.template:
        src: provisioning/templates/prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
        mode: '0644'

    - name: Restart Prometheus service
      ansible.builtin.systemd:
        name: prometheus
        state: restarted