- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup.yml


    - name: Create the Project VPC
      amazon.aws.ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        state: "{{state}}"
        tenancy: default
        dns_support: yes
        dns_hostnames: yes
      register: vpcout

   # - debug:
   #     var: vpcout

    - name: Create public subnets for EC2 Instances
      amazon.aws.ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{item.cidr}}"
        region: "{{region}}"
        az: "{{item.az}}"
        map_public: true
        tags:
          Name: "PubSub{{item.index}}"
      with_items:
        - { cidr: "{{PubSub1Cidr}}", az: "{{zone1}}", index: 1 }
        - { cidr: "{{PubSub2Cidr}}", az: "{{zone2}}", index: 2 }
        - { cidr: "{{PubSub3Cidr}}", az: "{{zone3}}", index: 3 }
      register: pubsubout





