- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup.yml


    - name: Create the Project VPC
      amazon.aws.ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        state: "{{state}}"
        tenancy: default
        dns_support: yes
        dns_hostnames: yes
      register: vpcout

   # - debug:
   #     var: vpcout

    - name: Create public subnets in Project VPC
      amazon.aws.ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{item.cidr}}"
        region: "{{region}}"
        az: "{{item.az}}"
        map_public: true
        tags:
          Name: "PubSub{{item.index}}"
      loop:
        - { cidr: "{{PubSub1Cidr}}", az: "{{zone1}}", index: 1 }
        - { cidr: "{{PubSub2Cidr}}", az: "{{zone2}}", index: 2 }
        - { cidr: "{{PubSub3Cidr}}", az: "{{zone3}}", index: 3 }
      register: pubsubout

    - name: Create private subnets in Project VPC
      amazon.aws.ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{item.cidr}}"
        region: "{{region}}"
        az: "{{item.az}}"
        tags:
          Name: "PrivSub{{item.index}}"
      loop:
        - { cidr: "{{PrivSub1Cidr}}", az: "{{zone1}}", index: 1 }
        - { cidr: "{{PrivSub2Cidr}}", az: "{{zone2}}", index: 2 }
        - { cidr: "{{PrivSub3Cidr}}", az: "{{zone3}}", index: 3 }
      register: privsubout

    - name: Create Internet gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{vpcout.vpc.id}}"
        state: "{{state}}"
        region: "{{region}}"
        tags:
          Name: VPC_IGW
      register: igw_out


    - name: Set up public subnet route table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: PublicRT
        subnets:
          - "{{ pubsubout.results[0].subnet.id }}"
          - "{{ pubsubout.results[1].subnet.id }}"
          - "{{ pubsubout.results[2].subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_out.gateway_id }}"
          - dest: ::/0
            gateway_id: "{{ igw_out.gateway_id }}"
      register: publicRT_out


    - name: Setting Facts
      ansible.builtin.set_fact:
        one_dict:
          vpcid:     "{{vpcout.vpc.id}}"
          pubsub1id: "{{pubsubout.results[0].subnet.id}}"
          pubsub2id: "{{pubsubout.results[1].subnet.id}}"
          pubsub3id: "{{pubsubout.results[2].subnet.id}}"
          privsub1id: " {{privsubout.results[0].subnet.id}}"
          privsub2id: " {{privsubout.results[1].subnet.id}}"
          privsub3id: " {{privsubout.results[2].subnet.id}}"
          igwid:      " {{igw_out.gateway_id}}"
          pubRTid:   " {{publicRT_out.route_table.id}}"
          cacheable: true

    - name: Saving Variables to a File
      copy:
        dest: vars/output_vars
        content:
         "vpcid: {{ vpcout.vpc.id }}
          pubsub1id: {{ pubsubout.results[0].subnet.id }}
          pubsub2id: {{ pubsubout.results[1].subnet.id }}
          pubsub3id: {{ pubsubout.results[2].subnet.id }}
          privsub1id: {{ privsubout.results[0].subnet.id }}
          privsub2id: {{ privsubout.results[1].subnet.id }}
          privsub3id: {{ privsubout.results[2].subnet.id }}
          igwid: {{ igw_out.gateway_id }}
          pubRTid: {{ publicRT_out.route_table.id }}"

