---
- name: Deploy Lambda function for syncing ASG instances
  hosts: localhost
  tasks:
    - name: Import IDs
      include_vars: ../vars/lambda_setup

    - name: Create IAM role for Lambda with administrative privileges
      amazon.aws.iam_role:
        name: LambdaRole
        assume_role_policy_document: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Service": "lambda.amazonaws.com"
                },
                "Action": "sts:AssumeRole"
              }
            ]
          }
        description: "Role for Lambda with administrative privileges"
      register: lambda_role

    - name: Attach AdministratorAccess policy to Lambda role
      community.aws.iam_policy:
        iam_name: "{{ lambda_role.iam_role.role_name }}"
        iam_type: role
        state: present
        policy_name: "AdministratorAccess"
        policy_json: "{{ lookup('template', 'templates/policy.json.j2') }}"


    - name: Upload Lambda code to S3
      aws_s3:
        bucket: "{{s3OUT}}"
        object: lambda_function.zip
        src: ./lambda_function.zip
        mode: put


    - name: Create Lambda function to sync S3 on instance launch
      amazon.aws.lambda:
        region: "{{region}}"
        state: present
        name: "asg-instance-sync"
        runtime: python3.9
        handler: lambda_function.lambda_handler
        s3_bucket: "{{ s3OUT }}"          # S3 bucket containing the Lambda code
        s3_key: "lambda_function.zip"      # Key of the Lambda code in the bucket
        role: "{{ lambda_role.iam_role.arn }}"
        timeout: 60
        memory_size: 128
      register: lambda_out


    - name: Create SNS topic for ASG triggers
      community.aws.sns_topic:
        region: "{{region}}"
        name: "asg-launch-triggers"
        state: present
      register: sns_topic

    - name: Create ASG lifecycle hook for instance launch
      command: >
        aws autoscaling put-lifecycle-hook
        --lifecycle-hook-name "NewInstanceLaunch"
        --auto-scaling-group-name "{{asgOUT}}"
        --lifecycle-transition "autoscaling:EC2_INSTANCE_LAUNCHING"
        --notification-target-arn "{{ sns_topic.sns_arn }}"
        --role-arn "{{ lambda_role.iam_role.arn }}"

    - name: Add SNS trigger to Lambda function
      community.aws.lambda_event:
        state: present
        function_name: "{{lambda_out.configuration.function_name}}"
        event_source_arn: "{{ sns_topic.arn }}"



