---
- name: Deploy Lambda function for syncing ASG instances using EventBridge
  hosts: localhost
  tasks:
    - name: Import IDs
      include_vars: ../vars/vpc-output_vars


    - name: Get the token for metadata access (on the local machine)
      ansible.builtin.shell: |
        TOKEN=$(curl -s -X PUT -H "X-aws-ec2-metadata-token-ttl-seconds: 300" http://169.254.169.254/latest/api/token)
        PUBLIC_IP=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/public-ipv4)
        echo "$PUBLIC_IP"
      register: ansible_machine_ip
      changed_when: false

    - debug:
        var: ansible_machine_ip.stdout

    - name: Create alarm SNS topic
      community.aws.sns_topic:
        name: "LambdaSNS"
        state: present
        region: "{{region}}"
        subscriptions:
          - endpoint: "http://{{ ansible_machine_ip.stdout }}/generic-webhook-trigger/invoke?token=12932"
            protocol: "http"
      register: SNS_out


    - name: Update Auto Scaling Group to add notifications
      community.aws.ec2_asg:
        name: "{{asgOUT}}"
        region: "{{ region }}"
        notification_topic: "{{SNS_out.sns_arn}}"  # Replace with your SNS topic ARN
        notification_types:
          - autoscaling:EC2_INSTANCE_LAUNCH
          - autoscaling:EC2_INSTANCE_TERMINATE
      register: asg_notification_update


