- name: Deploy Lambda function for syncing ASG instances using EventBridge
  hosts: localhost
  vars:
    token: "12932"
    aws_region: "us-west-2"
    lambda_execution_role: "arn:aws:iam::123456789012:role/lambda-execution-role"
    s3_bucket_name: "{{ s3OUT }}"
    lambda_zip_path: "/tmp/lambda_function.zip"
    lambda_code_path: "/tmp/lambda_function"

  tasks:
    - name: Import IDs
      include_vars: ../vars/vpc-output_vars

    - name: Create IAM role for Lambda with administrative privileges
      amazon.aws.iam_role:
        name: LambdaRole
        assume_role_policy_document: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Service": "lambda.amazonaws.com"
                },
                "Action": "sts:AssumeRole"
              }
            ]
          }
        description: "Role for Lambda with administrative privileges"
      register: lambda_role

    - name: Get the token for metadata access (on the local machine)
      ansible.builtin.shell: |
        TOKEN=$(curl -s -X PUT -H "X-aws-ec2-metadata-token-ttl-seconds: 300" http://169.254.169.254/latest/api/token)
        PUBLIC_IP=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/public-ipv4)
        echo "$PUBLIC_IP"
      register: ansible_machine_ip
      changed_when: false

    - name: Ensure the zip utility is installed
      package:
        name: zip
        state: present

    - name: Create directory for Lambda code
      file:
        path: "{{ lambda_code_path }}"
        state: directory
        mode: '0755'

    - name: Render Lambda function template with variables
      template:
        src: templates/lambda_function.py.j2
        dest: "{{ lambda_code_path }}/lambda_function.py"
      vars:
        jenkins_base_url: "http://{{ ansible_machine_ip.stdout }}:8080/generic-webhook-trigger/invoke"
        jenkins_token: "{{ token }}"

    - name: Install Python dependencies for Lambda
      pip:
        name:
          - requests
          # Add any other dependencies here
        extra_args: "-t {{ lambda_code_path }}"  # Install dependencies into the lambda_code_path directory

    - name: Create a zip archive of Lambda code with dependencies
      command: >
        zip -r "{{ lambda_zip_path }}" .
      args:
        chdir: "{{ lambda_code_path }}"  # Ensure the zip command is run in the correct directory


    - name: Upload Lambda code to S3
      aws_s3:
        bucket: "{{ s3OUT }}"
        object: lambda_function.zip
        src: "{{ lambda_zip_path }}"
        mode: put

    - name: Create Lambda function to sync S3 on instance launch
      amazon.aws.lambda:
        region: "{{ region }}"
        state: present
        name: "asg-instance-sync"
        runtime: python3.9
        handler: lambda_function.lambda_handler
        s3_bucket: "{{ s3OUT }}"
        s3_key: "lambda_function.zip"
        role: "{{ lambda_role.iam_role.arn }}"
        timeout: 60
        memory_size: 128
        environment_variables:
          S3_BUCKET_NAME: "{{ s3OUT }}"
      register: lambda_out

    - name: Get the Lambda function ARN without the version
      command: >
        aws lambda get-function
        --region "{{ region }}"
        --function-name "{{lambda_out.configuration.function_name}}"
        --query 'Configuration.FunctionArn'
        --output text
      register: lambda_function_arn

    - debug:
        var: "{{lambda_function_arn.stdout.strip()}}"

    - name: Create alarm SNS topic
      community.aws.sns_topic:
        name: "LambdaSNS"
        state: present
        region: "{{region}}"
      register: SNS_out

    - name: Update Auto Scaling Group to add notifications
      community.aws.ec2_asg:
        name: "{{asgOUT}}"
        region: "{{ region }}"
        notification_topic: "{{SNS_out.sns_arn}}"  # Replace with your SNS topic ARN
        notification_types:
          - autoscaling:EC2_INSTANCE_LAUNCH
      register: asg_notification_update

    - name: Subscribe Lambda function to SNS topic
      command: >
        aws sns subscribe
        --topic-arn "{{ SNS_out.sns_arn }}"
        --protocol lambda
        --notification-endpoint "{{ lambda_function_arn.stdout.strip() }}"
        --region "{{ region }}"

    - name: Grant SNS permission to invoke Lambda function
      command: >
        aws lambda add-permission
        --region "{{ region }}"
        --function-name "{{ lambda_function_arn.stdout.strip() }}"
        --principal sns.amazonaws.com
        --statement-id "SNSInvokePermissions"
        --action "lambda:InvokeFunction"
        --source-arn "{{ SNS_out.sns_arn }}"
