---
- name: Deploy Lambda function for syncing ASG instances using EventBridge
  hosts: localhost
  tasks:
    - name: Import IDs
      include_vars: ../vars/vpc-output_vars

    - name: Create IAM role for Lambda with administrative privileges
      amazon.aws.iam_role:
        name: LambdaRole
        assume_role_policy_document: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Service": "lambda.amazonaws.com"
                },
                "Action": "sts:AssumeRole"
              }
            ]
          }
        description: "Role for Lambda with administrative privileges"
      register: lambda_role

    - name: Attach AdministratorAccess policy to Lambda role
      community.aws.iam_policy:
        iam_name: "{{ lambda_role.iam_role.role_name }}"
        iam_type: role
        state: present
        policy_name: "AdministratorAccess"
        policy_json: "{{ lookup('template', 'templates/policy.json.j2') }}"

    - name: Upload Lambda code to S3
      aws_s3:
        bucket: "{{ s3OUT }}"
        object: lambda_function.zip
        src: ./lambda_function.zip
        mode: put

    - name: Create Lambda function to sync S3 on instance launch
      amazon.aws.lambda:
        region: "{{ region }}"
        state: present
        name: "asg-instance-sync"
        runtime: python3.9
        handler: lambda_function.lambda_handler
        s3_bucket: "{{ s3OUT }}"
        s3_key: "lambda_function.zip"
        role: "{{ lambda_role.iam_role.arn }}"
        timeout: 60
        memory_size: 128
        environment_variables:
          S3_BUCKET_NAME: "{{ s3OUT }}"  # Set your bucket name here
      register: lambda_out

    - name: Get the Lambda function ARN without the version
      command: >
        aws lambda get-function
        --region "{{ region }}"
        --function-name "{{lambda_out.configuration.function_name}}"
        --query 'Configuration.FunctionArn'
        --output text
      register: lambda_function_arn

    - name: Create EventBridge rule for ASG instance launch
      amazon.aws.cloudwatchevent_rule:
        name: "asg-instance-launch"
        description: "EventBridge rule for ASG instance launch to trigger Lambda function"
        state: present
        region: "{{region}}"
        event_pattern: |
          {
            "source": ["aws.autoscaling"],
            "detail-type": ["EC2 Instance Launch Successful"],
            "detail": {
              "Description": ["Launching a new EC2 instance"]
            }
          }
        targets:
          - id: MyTargetLambda
            arn: "{{lambda_function_arn}}"
            input_transformer:
              input_paths_map:
                instance: "$.detail.instance-id"
              input_template: '{"instance-id": "<instance>"}'
      register: eventbridge_rule


    - name: Grant EventBridge permission to invoke Lambda function
      command: >
        aws lambda add-permission
        --region "{{ region }}"
        --function-name "{{ lambda_out.configuration.function_name }}"
        --principal events.amazonaws.com
        --statement-id "EventBridgeInvokePermission"
        --action "lambda:InvokeFunction"
        --source-arn "{{ eventbridge_rule.rule.arn }}"
