---
- name: Install Kubernetes control plane
  hosts: control
  become: yes
  gather_facts: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: present

    - name: Add Kubernetes APT key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Remove duplicate Grafana repository configurations
      file:
        path: "/etc/apt/sources.list.d/grafana.list"
        state: absent

    - name: Add Kubernetes APT repository
      apt_repository:
        repo: "deb http://apt.kubernetes.io/ kubernetes-{{ ansible_distribution_release }} main"
        state: present
        filename: "kubernetes"
        update_cache: yes
      tags: k8s_repo


    - name: Install Kubernetes packages
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Hold Kubernetes packages at current version
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        lock: yes
