---
- name: Update Prometheus config to scrape Node Exporters
  hosts: control
  become: yes
  tasks:
    - name: Backup the existing prometheus.yml
      ansible.builtin.copy:
        src: /etc/prometheus/prometheus.yml
        dest: /etc/prometheus/prometheus.yml.bak
        remote_src: yes

    - name: Generate list of node exporters from inventory
      ansible.builtin.template:
        src: templates/prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
        mode: '0644'

    - name: Restart Prometheus service
      ansible.builtin.systemd:
        name: prometheus
        state: restarted
