---
- name: s3 mounting play
  hosts: websrvgrp
  become: yes
  gather_facts: False
  vars:
    mount_path: "/var/www/html"
  tasks:
    - name: Import IDs
      include_vars: ../vars/vpc-output_vars

    - name: Clear /var/www/html/ in worker nodes
      ansible.builtin.shell: rm -rf {{mount_path}}/*


    - name: Install the package "s3fs-fuse"
      ansible.builtin.apt:
        name:
          - s3fs
        state: present
      become: true

    - name: Give ownership to www-data
      ansible.builtin.shell: |
        sudo chown -R www-data:www-data {{mount_path}}
        sudo chown -R www-data:www-data {{mount_path}}/*
        sudo chmod -R 755 {{mount_path}}

    - name: Mount S3 bucket to /var/www/html using s3fs
      shell: |
        echo "{{ s3OUT }} {{ mount_path }} fuse.s3fs _netdev,allow_other,iam_role=auto 0 0" >> /etc/fstab
        s3fs {{ s3OUT }} {{ mount_path }} -o iam_role=auto,allow_other
      become: true

