---
- name: Install stress package on machines
  hosts: websrvgrp
  become: yes
  gather_facts: no
  tasks:
    - name: Update APT package index
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install stress package
      ansible.builtin.apt:
        name: stress
        state: present